### THE COMPANY OVERVIEW
### THE PROJECT OVERVIEW
### THE BUSINESS PROBLEM
. They understaffed during surge(Refers to a scenario where more than expected patients roll in but definitely not everyday) and overstaffed during predictable roles. It will also affect the firm or hospital reputation and customers/patients might loose interest.
. Decision problem
### THE BUSINESS IMPACT
. Staffs get overwhelmed
Inaccuracy in data compilation
### THE PROJECT OBJECTIVE
.Forecast Accuracy benchmark
.Identify their demand drivers
.Create a volume forecast model
.Translate the forecast into a guidiance/sfaffing guidiance
.To understand your data scan throught the results the head function, info function,

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as  plt
import seaborn as sns

In [2]:
### LOADING DATASET

data_frame = pd.read_csv(r"C:\Users\Ifeoluwa\OneDrive\Documents\Nexora_Care\data\raw\AppointmentRecords.csv")
data_frame.head(6)

,AppointmentID,ClinicID,ClinicName,ClinicType,PatientID,ProviderID,AppointmentDateTime,AppointmentType,Status,BookingChannel,BookingLeadTimeDays,IsHoliday,HolidayName,SeasonFlag,ChronicConditionFlag
0,529385,2,Nexora Care - Lakeside,Multi-Specialty,103642,202,2024-01-01 08:00,New Patient,Completed,Online,2,True,New Year's Day,Flu Season,False
1,500000,1,Nexora Care - Riverside,Primary Care,101551,101,2024-01-01 08:30,New Patient,No-Show,Online,18,True,New Year's Day,Flu Season,False
2,500011,1,Nexora Care - Riverside,Primary Care,100260,104,2024-01-01 08:30,Follow-Up,Completed,Referral,4,True,New Year's Day,Flu Season,False
3,575066,3,Nexora Care - Downtown Express,Telehealth-Forward,104923,301,2024-01-01 09:45,Urgent,Completed,Online,0,True,New Year's Day,Flu Season,False
4,500008,1,Nexora Care - Riverside,Primary Care,101124,104,2024-01-01 09:45,Telehealth,Completed,Phone,2,True,New Year's Day,Flu Season,False
5,500012,1,Nexora Care - Riverside,Primary Care,100457,103,2024-01-01 10:45,Telehealth,Completed,Online,13,True,New Year's Day,Flu Season,True

In [3]:
data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 129353 entries, 0 to 129352
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   AppointmentID         129353 non-null  int64
 1   ClinicID              129353 non-null  int64
 2   ClinicName            129353 non-null  str
 3   ClinicType            129353 non-null  str
 4   PatientID             129353 non-null  int64
 5   ProviderID            129353 non-null  int64
 6   AppointmentDateTime   129353 non-null  str
 7   AppointmentType       129353 non-null  str
 8   Status                129353 non-null  str
 9   BookingChannel        129353 non-null  str
 10  BookingLeadTimeDays   129353 non-null  int64
 11  IsHoliday             129353 non-null  bool
 12  HolidayName           939 non-null     str
 13  SeasonFlag            129353 non-null  str
 14  ChronicConditionFlag  129353 non-null  bool
dtypes: bool(2), int64(5), str(8)
memory usage: 13.1 MB

In [4]:
### FOR NUMERICAL COLUMNS, WE CAN GET THE STATISTICAL SUMMARY OF THE DATASET USING THE DESCRIBE FUNCTION
data_frame.describe()

,AppointmentID,ClinicID,PatientID,ProviderID,BookingLeadTimeDays
count,129353.000000,129353.000000,129353.000000,129353.000000,129353.000000
mean,564676.000000,2.417864,103553.485385,245.290005,8.704267
std,37341.139023,1.071525,2020.941152,107.165883,7.641921
min,500000.000000,1.000000,100000.000000,101.000000,0.000000
25%,532338.000000,2.000000,101812.000000,201.000000,3.000000
50%,564676.000000,2.000000,103547.000000,205.000000,7.000000
75%,597014.000000,3.000000,105178.000000,306.000000,12.000000
max,629352.000000,4.000000,107279.000000,406.000000,60.000000

In [5]:
### FOR CATEGORICAL COLUMNS, WE CAN GET THE STATISTICAL SUMMARY OF THE DATASET USING THE DESCRIBE FUNCTION
data_frame.describe(include='object')

C:\Users\Ifeoluwa\AppData\Local\Temp\ipykernel_22696\2098752137.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data_frame.describe(include='object')

,ClinicName,ClinicType,AppointmentDateTime,AppointmentType,Status,BookingChannel,HolidayName,SeasonFlag
count,129353,129353,129353,129353,129353,129353,939,129353
unique,4,3,30287,4,4,4,13,3
top,Nexora Care - Lakeside,Primary Care,2025-01-02 13:45,Follow-Up,Completed,Online,Christmas Eve,Standard
freq,45681,58526,19,57859,109040,57061,105,64015

### DATA CLEANING
1. Missing Values: Check for missing values in the dataset and decide how to handle them (e.g., imputation, removal).
2. Duplicates: Identify and remove any duplicate records in the dataset.
3. Inconsistencies in Data: Look for inconsistencies in categorical variables (e.g., different spellings or formats) and standardize them.

In [20]:
data_frame.isnull()

,AppointmentID,ClinicID,ClinicName,ClinicType,PatientID,ProviderID,AppointmentDateTime,AppointmentType,Status,BookingChannel,BookingLeadTimeDays,IsHoliday,HolidayName,SeasonFlag,ChronicConditionFlag
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129348,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
129349,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
129350,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
129351,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
129352,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [24]:
data_frame.isnull().sum()

AppointmentID                0
ClinicID                     0
ClinicName                   0
ClinicType                   0
PatientID                    0
ProviderID                   0
AppointmentDateTime          0
AppointmentType              0
Status                       0
BookingChannel               0
BookingLeadTimeDays          0
IsHoliday                    0
HolidayName             128414
SeasonFlag                   0
ChronicConditionFlag         0
dtype: int64

In [28]:
data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 129353 entries, 0 to 129352
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   AppointmentID         129353 non-null  int64
 1   ClinicID              129353 non-null  int64
 2   ClinicName            129353 non-null  str
 3   ClinicType            129353 non-null  str
 4   PatientID             129353 non-null  int64
 5   ProviderID            129353 non-null  int64
 6   AppointmentDateTime   129353 non-null  str
 7   AppointmentType       129353 non-null  str
 8   Status                129353 non-null  str
 9   BookingChannel        129353 non-null  str
 10  BookingLeadTimeDays   129353 non-null  int64
 11  IsHoliday             129353 non-null  bool
 12  HolidayName           939 non-null     str
 13  SeasonFlag            129353 non-null  str
 14  ChronicConditionFlag  129353 non-null  bool
dtypes: bool(2), int64(5), str(8)
memory usage: 13.1 MB

In [29]:
data_frame.isnull().sum()

AppointmentID                0
ClinicID                     0
ClinicName                   0
ClinicType                   0
PatientID                    0
ProviderID                   0
AppointmentDateTime          0
AppointmentType              0
Status                       0
BookingChannel               0
BookingLeadTimeDays          0
IsHoliday                    0
HolidayName             128414
SeasonFlag                   0
ChronicConditionFlag         0
dtype: int64

In [14]:
data_frame.nunique()

AppointmentID           129353
ClinicID                     4
ClinicName                   4
ClinicType                   3
PatientID                 7109
ProviderID                  24
AppointmentDateTime      30287
AppointmentType              4
Status                       4
BookingChannel               4
BookingLeadTimeDays         61
IsHoliday                    2
HolidayName                 13
SeasonFlag                   3
ChronicConditionFlag         2
dtype: int64

In [33]:
data_frame['HolidayName'] = data_frame['HolidayName'].fillna('Not a Holiday')

In [34]:
data_frame.isnull().sum()

AppointmentID           0
ClinicID                0
ClinicName              0
ClinicType              0
PatientID               0
ProviderID              0
AppointmentDateTime     0
AppointmentType         0
Status                  0
BookingChannel          0
BookingLeadTimeDays     0
IsHoliday               0
HolidayName             0
SeasonFlag              0
ChronicConditionFlag    0
dtype: int64

In [35]:
data_frame.duplicated().sum()

np.int64(0)

In [36]:
data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 129353 entries, 0 to 129352
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   AppointmentID         129353 non-null  int64
 1   ClinicID              129353 non-null  int64
 2   ClinicName            129353 non-null  str
 3   ClinicType            129353 non-null  str
 4   PatientID             129353 non-null  int64
 5   ProviderID            129353 non-null  int64
 6   AppointmentDateTime   129353 non-null  str
 7   AppointmentType       129353 non-null  str
 8   Status                129353 non-null  str
 9   BookingChannel        129353 non-null  str
 10  BookingLeadTimeDays   129353 non-null  int64
 11  IsHoliday             129353 non-null  bool
 12  HolidayName           129353 non-null  str
 13  SeasonFlag            129353 non-null  str
 14  ChronicConditionFlag  129353 non-null  bool
dtypes: bool(2), int64(5), str(8)
memory usage: 13.1 MB

In [39]:
data_frame.describe()

,AppointmentID,ClinicID,PatientID,ProviderID,BookingLeadTimeDays
count,129353.000000,129353.000000,129353.000000,129353.000000,129353.000000
mean,564676.000000,2.417864,103553.485385,245.290005,8.704267
std,37341.139023,1.071525,2020.941152,107.165883,7.641921
min,500000.000000,1.000000,100000.000000,101.000000,0.000000
25%,532338.000000,2.000000,101812.000000,201.000000,3.000000
50%,564676.000000,2.000000,103547.000000,205.000000,7.000000
75%,597014.000000,3.000000,105178.000000,306.000000,12.000000
max,629352.000000,4.000000,107279.000000,406.000000,60.000000

In [40]:
for col in ['AppointmentID', 'ClinicID', 'ClinicName', 'ClinicType', 'ProviderID', 'BookingChannel','PatientID', 'AppointmentDateTime', 'AppointmentType', 'Status', 'HolidayName', 'ChronicConditionFlag', 'SeasonFlag', 'IsHoliday', 'BookingLeadTimeDays']:
    print(col, data_frame[col].unique())
    print()

AppointmentID [529385 500000 500011 ... 529376 629337 575056]

ClinicID [2 1 3 4]

ClinicName <StringArray>
[        'Nexora Care - Lakeside',        'Nexora Care - Riverside',
 'Nexora Care - Downtown Express',        'Nexora Care - Hillcrest']
Length: 4, dtype: str

ClinicType <StringArray>
['Multi-Specialty', 'Primary Care', 'Telehealth-Forward']
Length: 3, dtype: str

ProviderID [202 101 104 301 103 205 306 105 204 201 102 106 302 304 203 206 303 305
 403 406 401 405 402 404]

BookingChannel <StringArray>
['Online', 'Referral', 'Phone', 'Walk-In']
Length: 4, dtype: str

PatientID [103642 101551 100260 ... 101190 105796 105479]

AppointmentDateTime <StringArray>
['2024-01-01 08:00', '2024-01-01 08:30', '2024-01-01 09:45',
 '2024-01-01 10:45', '2024-01-01 11:00', '2024-01-01 11:15',
 '2024-01-01 11:45', '2024-01-01 12:00', '2024-01-01 12:15',
 '2024-01-01 12:30',
 ...
 '2025-12-31 14:15', '2025-12-31 14:30', '2025-12-31 15:00',
 '2025-12-31 15:15', '2025-12-31 15:30', '2025-12-31 16:00',
 '2025-12-31 16:15', '2025-12-31 16:30', '2025-12-31 16:45',
 '2025-12-31 17:45']
Length: 30287, dtype: str

AppointmentType <StringArray>
['New Patient', 'Follow-Up', 'Urgent', 'Telehealth']
Length: 4, dtype: str

Status <StringArray>
['Completed', 'No-Show', 'Cancelled', 'Rescheduled']
Length: 4, dtype: str

HolidayName <StringArray>
[        'New Year's Day',             'No Holiday',                'MLK Day',
        'Presidents' Day',           'Memorial Day',             'Juneteenth',
       'Independence Day',              'Labor Day',           'Veterans Day',
           'Thanksgiving', 'Day After Thanksgiving',          'Christmas Eve',
          'Christmas Day',         'New Year's Eve']
Length: 14, dtype: str

ChronicConditionFlag [False  True]

SeasonFlag <StringArray>
['Flu Season', 'Allergy Season', 'Standard']
Length: 3, dtype: str

IsHoliday [ True False]

BookingLeadTimeDays [ 2 18  4  0 13  6 10 11  3  8  1 14  5 24 15 12 29  7 16 17 19 22 42 25
  9 26 44 21 39 23 20 48 28 33 45 38 40 30 37 32 34 31 36 27 35 46 43 56
 60 54 41 59 55 49 50 47 58 53 52 57 51]

In [41]:
for col in ['AppointmentType', 'Status', 'HolidayName', 'SeasonFlag']:
    print(col, data_frame[col].unique())
    print()

AppointmentType <StringArray>
['New Patient', 'Follow-Up', 'Urgent', 'Telehealth']
Length: 4, dtype: str

Status <StringArray>
['Completed', 'No-Show', 'Cancelled', 'Rescheduled']
Length: 4, dtype: str

HolidayName <StringArray>
[        'New Year's Day',             'No Holiday',                'MLK Day',
        'Presidents' Day',           'Memorial Day',             'Juneteenth',
       'Independence Day',              'Labor Day',           'Veterans Day',
           'Thanksgiving', 'Day After Thanksgiving',          'Christmas Eve',
          'Christmas Day',         'New Year's Eve']
Length: 14, dtype: str

SeasonFlag <StringArray>
['Flu Season', 'Allergy Season', 'Standard']
Length: 3, dtype: str

In [44]:
data_frame.to_csv(r"C:\Users\Ifeoluwa\OneDrive\Documents\Nexora_Care\data\processed\cleaned_appointments.csv", index=False)

In [6]:
data_frame['AppointmentDateTime'] = pd.to_datetime(data_frame['AppointmentDateTime'])

In [12]:
data_frame.shape

(129353, 15)

In [7]:
data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 129353 entries, 0 to 129352
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   AppointmentID         129353 non-null  int64
 1   ClinicID              129353 non-null  int64
 2   ClinicName            129353 non-null  str
 3   ClinicType            129353 non-null  str
 4   PatientID             129353 non-null  int64
 5   ProviderID            129353 non-null  int64
 6   AppointmentDateTime   129353 non-null  datetime64[us]
 7   AppointmentType       129353 non-null  str
 8   Status                129353 non-null  str
 9   BookingChannel        129353 non-null  str
 10  BookingLeadTimeDays   129353 non-null  int64
 11  IsHoliday             129353 non-null  bool
 12  HolidayName           939 non-null     str
 13  SeasonFlag            129353 non-null  str
 14  ChronicConditionFlag  129353 non-null  bool
dtypes: bool(2), datetime64[us](1), int64(5), str(7)
memory usage: 13.1 MB

In [10]:
data_frame['HolidayName'].value_counts()

HolidayName
Christmas Eve             105
Thanksgiving               87
New Year's Eve             87
Christmas Day              80
New Year's Day             74
Presidents' Day            73
Juneteenth                 72
Day After Thanksgiving     64
Independence Day           63
MLK Day                    59
Veterans Day               59
Memorial Day               58
Labor Day                  58
Name: count, dtype: int64