In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data_frame = pd.read_csv(r"C:\Users\Ifeoluwa\OneDrive\Documents\Nexora_Care\data\processed\eda_appointments.csv")

In [3]:
data_frame.head()

,AppointmentID,ClinicID,ClinicName,ClinicType,PatientID,ProviderID,AppointmentDateTime,AppointmentType,Status,BookingChannel,BookingLeadTimeDays,IsHoliday,HolidayName,SeasonFlag,ChronicConditionFlag
0,529385,2,Nexora Care - Lakeside,Multi-Specialty,103642,202,2024-01-01 08:00:00,New Patient,Completed,Online,2,True,New Year's Day,Flu Season,False
1,500000,1,Nexora Care - Riverside,Primary Care,101551,101,2024-01-01 08:30:00,New Patient,No-Show,Online,18,True,New Year's Day,Flu Season,False
2,500011,1,Nexora Care - Riverside,Primary Care,100260,104,2024-01-01 08:30:00,Follow-Up,Completed,Referral,4,True,New Year's Day,Flu Season,False
3,575066,3,Nexora Care - Downtown Express,Telehealth-Forward,104923,301,2024-01-01 09:45:00,Urgent,Completed,Online,0,True,New Year's Day,Flu Season,False
4,500008,1,Nexora Care - Riverside,Primary Care,101124,104,2024-01-01 09:45:00,Telehealth,Completed,Phone,2,True,New Year's Day,Flu Season,False

In [4]:
data_frame['AppointmentDateTime'] = pd.to_datetime(data_frame['AppointmentDateTime'])

In [5]:
data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 129353 entries, 0 to 129352
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   AppointmentID         129353 non-null  int64
 1   ClinicID              129353 non-null  int64
 2   ClinicName            129353 non-null  str
 3   ClinicType            129353 non-null  str
 4   PatientID             129353 non-null  int64
 5   ProviderID            129353 non-null  int64
 6   AppointmentDateTime   129353 non-null  datetime64[us]
 7   AppointmentType       129353 non-null  str
 8   Status                129353 non-null  str
 9   BookingChannel        129353 non-null  str
 10  BookingLeadTimeDays   129353 non-null  int64
 11  IsHoliday             129353 non-null  bool
 12  HolidayName           129353 non-null  str
 13  SeasonFlag            129353 non-null  str
 14  ChronicConditionFlag  129353 non-null  bool
dtypes: bool(2), datetime64[us](1), int64(5), str(7)
memory usage: 13.1 MB

In [9]:
data_frame = pd.read_csv(r"C:\Users\Ifeoluwa\OneDrive\Documents\Nexora_Care\data\processed\cleaned_appointments.csv")

In [10]:
data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 129353 entries, 0 to 129352
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   AppointmentID         129353 non-null  int64
 1   ClinicID              129353 non-null  int64
 2   ClinicName            129353 non-null  str
 3   ClinicType            129353 non-null  str
 4   PatientID             129353 non-null  int64
 5   ProviderID            129353 non-null  int64
 6   AppointmentDateTime   129353 non-null  str
 7   AppointmentType       129353 non-null  str
 8   Status                129353 non-null  str
 9   BookingChannel        129353 non-null  str
 10  BookingLeadTimeDays   129353 non-null  int64
 11  IsHoliday             129353 non-null  bool
 12  HolidayName           129353 non-null  str
 13  SeasonFlag            129353 non-null  str
 14  ChronicConditionFlag  129353 non-null  bool
dtypes: bool(2), int64(5), str(8)
memory usage: 13.1 MB

In [14]:
data_frame['AppointmentDateTime'] =pd.to_datetime(data_frame['AppointmentDateTime'])

In [23]:
data_frame['AppointmentHour'] = data_frame['AppointmentDateTime'].dt.hour
data_frame['AppointmentDayOfWeek'] = data_frame['AppointmentDateTime'].dt.day_name()
data_frame['AppointmentMonth'] = data_frame['AppointmentDateTime'].dt.month_name()

In [18]:
data_frame.head()

,AppointmentID,ClinicID,ClinicName,ClinicType,PatientID,ProviderID,AppointmentDateTime,AppointmentType,Status,BookingChannel,BookingLeadTimeDays,IsHoliday,HolidayName,SeasonFlag,ChronicConditionFlag,AppointmentHour,AppointmentDayOfWeek,AppointmentMonth
0,529385,2,Nexora Care - Lakeside,Multi-Specialty,103642,202,2024-01-01 08:00:00,New Patient,Completed,Online,2,True,New Year's Day,Flu Season,False,8,Monday,January
1,500000,1,Nexora Care - Riverside,Primary Care,101551,101,2024-01-01 08:30:00,New Patient,No-Show,Online,18,True,New Year's Day,Flu Season,False,8,Monday,January
2,500011,1,Nexora Care - Riverside,Primary Care,100260,104,2024-01-01 08:30:00,Follow-Up,Completed,Referral,4,True,New Year's Day,Flu Season,False,8,Monday,January
3,575066,3,Nexora Care - Downtown Express,Telehealth-Forward,104923,301,2024-01-01 09:45:00,Urgent,Completed,Online,0,True,New Year's Day,Flu Season,False,9,Monday,January
4,500008,1,Nexora Care - Riverside,Primary Care,101124,104,2024-01-01 09:45:00,Telehealth,Completed,Phone,2,True,New Year's Day,Flu Season,False,9,Monday,January

In [19]:
data_frame['IsWeekend'] = data_frame['AppointmentDayOfWeek'].isin(['Saturday', 'Sunday'])

In [20]:
data_frame.head()

,AppointmentID,ClinicID,ClinicName,ClinicType,PatientID,ProviderID,AppointmentDateTime,AppointmentType,Status,BookingChannel,BookingLeadTimeDays,IsHoliday,HolidayName,SeasonFlag,ChronicConditionFlag,AppointmentHour,AppointmentDayOfWeek,AppointmentMonth,IsWeekend
0,529385,2,Nexora Care - Lakeside,Multi-Specialty,103642,202,2024-01-01 08:00:00,New Patient,Completed,Online,2,True,New Year's Day,Flu Season,False,8,Monday,January,False
1,500000,1,Nexora Care - Riverside,Primary Care,101551,101,2024-01-01 08:30:00,New Patient,No-Show,Online,18,True,New Year's Day,Flu Season,False,8,Monday,January,False
2,500011,1,Nexora Care - Riverside,Primary Care,100260,104,2024-01-01 08:30:00,Follow-Up,Completed,Referral,4,True,New Year's Day,Flu Season,False,8,Monday,January,False
3,575066,3,Nexora Care - Downtown Express,Telehealth-Forward,104923,301,2024-01-01 09:45:00,Urgent,Completed,Online,0,True,New Year's Day,Flu Season,False,9,Monday,January,False
4,500008,1,Nexora Care - Riverside,Primary Care,101124,104,2024-01-01 09:45:00,Telehealth,Completed,Phone,2,True,New Year's Day,Flu Season,False,9,Monday,January,False

In [21]:
data_frame.head()

,AppointmentID,ClinicID,ClinicName,ClinicType,PatientID,ProviderID,AppointmentDateTime,AppointmentType,Status,BookingChannel,BookingLeadTimeDays,IsHoliday,HolidayName,SeasonFlag,ChronicConditionFlag,AppointmentHour,AppointmentDayOfWeek,AppointmentMonth,IsWeekend
0,529385,2,Nexora Care - Lakeside,Multi-Specialty,103642,202,2024-01-01 08:00:00,New Patient,Completed,Online,2,True,New Year's Day,Flu Season,False,8,Monday,January,False
1,500000,1,Nexora Care - Riverside,Primary Care,101551,101,2024-01-01 08:30:00,New Patient,No-Show,Online,18,True,New Year's Day,Flu Season,False,8,Monday,January,False
2,500011,1,Nexora Care - Riverside,Primary Care,100260,104,2024-01-01 08:30:00,Follow-Up,Completed,Referral,4,True,New Year's Day,Flu Season,False,8,Monday,January,False
3,575066,3,Nexora Care - Downtown Express,Telehealth-Forward,104923,301,2024-01-01 09:45:00,Urgent,Completed,Online,0,True,New Year's Day,Flu Season,False,9,Monday,January,False
4,500008,1,Nexora Care - Riverside,Primary Care,101124,104,2024-01-01 09:45:00,Telehealth,Completed,Phone,2,True,New Year's Day,Flu Season,False,9,Monday,January,False

In [31]:
def lead_time_booking(days):
    if days == 0:
        return 'Same Day'
    elif days <= 7:
        return 'Within a Week'
    elif days <= 30:
        return 'Within a Month'
    else:
        return 'Over a Month'

data_frame['LeadTimeCategory'] = data_frame['BookingLeadTimeDays'].apply(lead_time_booking)

In [29]:
data_frame['IsNoShow'] = (data_frame['Status'] == 'No-Show').astype(int)

In [32]:
data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 129353 entries, 0 to 129352
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   AppointmentID         129353 non-null  int64
 1   ClinicID              129353 non-null  int64
 2   ClinicName            129353 non-null  str
 3   ClinicType            129353 non-null  str
 4   PatientID             129353 non-null  int64
 5   ProviderID            129353 non-null  int64
 6   AppointmentDateTime   129353 non-null  datetime64[us]
 7   AppointmentType       129353 non-null  str
 8   Status                129353 non-null  str
 9   BookingChannel        129353 non-null  str
 10  BookingLeadTimeDays   129353 non-null  int64
 11  IsHoliday             129353 non-null  bool
 12  HolidayName           129353 non-null  str
 13  SeasonFlag            129353 non-null  str
 14  ChronicConditionFlag  129353 non-null  bool
 15  AppointmentHour       129353 non-null  int32
 16  AppointmentDayOfWeek  129353 non-null  str
 17  AppointmentMonth      129353 non-null  str
 18  IsWeekend             129353 non-null  bool
 19  IsNoShow              129353 non-null  int64
 20  LeadTimeCategory      129353 non-null  str
dtypes: bool(3), datetime64[us](1), int32(1), int64(6), str(10)
memory usage: 17.6 MB

In [39]:
data_frame[['LeadTimeCategory', 'IsNoShow', 'IsWeekend']].sample(50)

       LeadTimeCategory  IsNoShow  IsWeekend
80325          Same Day         0       True
45905    Within a Month         0      False
123013    Within a Week         0      False
96561    Within a Month         0      False
126323   Within a Month         1      False
68670    Within a Month         0      False
56529    Within a Month         1      False
25889    Within a Month         0      False
39415    Within a Month         0      False
89973          Same Day         0      False
7566     Within a Month         0      False
91902     Within a Week         0      False
13667     Within a Week         0      False
84999    Within a Month         0      False
14107     Within a Week         0      False
20531    Within a Month         0      False
82808    Within a Month         0      False
11101      Over a Month         0       True
22490     Within a Week         0      False
109889     Over a Month         1      False
17570    Within a Month         0      False
87495     Within a Week         0      False
111658   Within a Month         0      False
65614     Within a Week         0      False
100452   Within a Month         0      False
59419    Within a Month         0      False
54094    Within a Month         0      False
9107     Within a Month         0      False
35920     Within a Week         0      False
54827    Within a Month         0      False
57115    Within a Month         0      False
105637   Within a Month         0      False
109425   Within a Month         0      False
62827    Within a Month         0      False
40354     Within a Week         0      False
116358   Within a Month         0      False
8656      Within a Week         0      False
52722     Within a Week         0       True
13200    Within a Month         0      False
87442    Within a Month         0      False
8362     Within a Month         0      False
50905     Within a Week         0      False
52659     Within a Week         1       True
62473          Same Day         0      False
87140     Within a Week         0      False
125129   Within a Month         0      False
86221     Within a Week         0      False
104616   Within a Month         0      False
28006    Within a Month         0      False
54518    Within a Month         0      False

In [42]:
data_frame.to_csv(r"C:\Users\Ifeoluwa\OneDrive\Documents\Nexora_Care\data\processed\Feature_Eng_appointments.csv", index=False)

In [44]:
data_frame[['BookingLeadTimeDays', 'LeadTimeCategory']].sample(10)

        BookingLeadTimeDays LeadTimeCategory
50873                     6    Within a Week
10062                     6    Within a Week
25925                    10   Within a Month
63036                    10   Within a Month
30953                     8   Within a Month
34989                     7    Within a Week
41619                     8   Within a Month
104772                    3    Within a Week
32825                    24   Within a Month
10                        3    Within a Week

In [45]:
data_frame[['Status', 'IsNoShow']].sample(10)

           Status  IsNoShow
81578   Cancelled         0
109905  Completed         0
68978   Completed         0
127818  Completed         0
101445  Completed         0
119176    No-Show         1
60267   Completed         0
1186    Completed         0
123072  Cancelled         0
38235   Completed         0